### ISSUE TITLE
failed to create symbolic link

### ISSUE THREAD

**Issue by milkboy007** [ViewTouch/viewtouch#10]
root@debian:~/viewtouch/build# ln -s /usr/viewtouch/dat/ dat ..
ln: failed to create symbolic link ‘../dat’: File exists
on debian 8.1 fresh install

is the /usr/viewtouch/dat/ supoosed to soflink link folder located at ~/viewtouch/??

**Comment by GeneMosher** [comment]
Yes.  Having the symbolic link in ~/viewtouch avoids the error message.  Running the code successfully does not require this; it only makes the linker happy.

**Comment by GeneMosher** [comment]
I am reopening this because there is a longstanding issue which is somewhat related to it.

When building ViewTouch from scratch and running it the first time the required /usr/viewtouch/dat directory does not exist and the program then fails to run.  If, however, usr/viewtouch/dat has been manually created by user viewtouch with the mkdir command then the program will run and the program will subsequently and automatically create many of the directories and files it needs wirhin the /dat directory.  I would ask that someone might enhance the code so that if ViewTouch does not find h/usr/viewtouch/dat, (i.e., if it does not yet exist) that the program would then create the /usr/viewtouch/dat directory.

Now, with regard to the reason this issue was opened originally, and because the error is still being reported, I would be pleased if either the symbolic link could be automatically generated by a line of code when it does not yet exist, or if the linker could be made smart enough to not report it, since it isn't really an error.
