### ISSUE TITLE
The 'install' target fails: file INSTALL cannot find   "/usr/ports/misc/viewtouch/work/viewtouch-19.04.1/dat"

### ISSUE THREAD

**Issue by yurivict** [ViewTouch/viewtouch#101]
```
-- Up-to-date: /usr/ports/misc/viewtouch/work/stage/usr/local/viewtouch/bin/runonce
CMake Error at cmake_install.cmake:149 (file):
  file INSTALL cannot find
  "/usr/ports/misc/viewtouch/work/viewtouch-19.04.1/dat".


FAILED: CMakeFiles/install/strip.util 
cd /usr/ports/misc/viewtouch/work/.build && /usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
ninja: build stopped: subcommand failed.
```

**Comment by yurivict** [comment]
This line https://github.com/ViewTouch/viewtouch/blob/master/CMakeLists.txt#L290 doesn't have a corresponding directory/file to install.

**Comment by NeroBurner** [comment]
yes, I've been thinking about that line for the last week :thinking: 

When I started viewtouch I created that missing dat folder in my source and never again touched it. I used the bootstrap files provided here http://www.viewtouch.com/vt_data.html.

I think I'll modify it so that CMake installs the `dat` folder from the source directory if it exists and otherwise issues a warning with the link to the vt_data files

**Comment by NeroBurner** [comment]
Additionally I think we should add the `make install` command to the CI jobs as we would have cought this error earlier

**Comment by NeroBurner** [comment]
thanks again for pointing out this long standing nuisance
