### ISSUE TITLE
Code Errors (two)

### ISSUE THREAD

**Issue by GeneMosher** [ViewTouch/viewtouch#117]
Two code errors which cause a program exit have been reported.  To see them, Logon as Editor (User ID 42) > Start > Manager's Gateway

First code error: > Reports > Receipts Balance 

The next page which should appear is System Page -62, Accountant's Report.  Sometimes the program exits before System Page -62 displays and sometimes the program exits after System Page -62 displays but when any button on System Page -62 is selected.

Second code error: > Configuration > Customize Job Titles, Families, Phrases

The program exits when Page 13 (of 16) is selected.

Hopefully it's useful to mention that both of these program exits have shown themselves and were fixed in the past.

**Comment by NeroBurner** [comment]
Can't reproduce segfault 1

---

Segfault 2 is because Page 13 has no last label entry and my `Str` class doesn't like `nullptr` as argument to `Set(const char*)`. What is the expected behavior on this page for the last form? I would either set the label to an empty string, then the input field is visible, but has no label on the left (see screenshot below). Or I could disable the form in this case and there would be no last entry visible

![20210511_viewtouch_page13](https://user-images.githubusercontent.com/9076163/117871981-5aa0da00-b29e-11eb-940b-570b20bb43f5.png)

The line with the segfault: https://github.com/ViewTouch/viewtouch/blob/44046769bffce7258b0ace11d8c7d9851e596639/zone/phrase_zone.cc#L73

```cpp
f->label.Set(PhraseData[idx].text);
```
`PhraseData[idx].text` is a `nullptr`

**Comment by GeneMosher** [comment]
Thanks for the prompt code repair, NeroBurner !  I made a clean start of the /usr/viewtouch/dat directory and was able to determine that the first of the two Code Errors I made mention of here seems to be a problem with data being fed to the program.  I will look into this further and update when I have more to add with regard to this.
