### ISSUE TITLE
After copying VT /dat to Raspberry Pi, Revenu shows on wrong day

### ISSUE THREAD

**Issue by jcrafty** [ViewTouch/viewtouch#126]
Issue Overview:  Transactions/sales are not on the correct date after copying /dat folder to new Raspberry Pi setup.

Issue Details:
After installing the most recently available ViewTouch image  on a new Raspberry Pi 4 and following the process of copying of /dat folder from old NUC to the new Pi I find the dates on my data are shifted 5 days when viewing "Today's Revenue & Productivity" or "Menu Item Performance - (Archives)  

I took a backup of the /dat folder on 3 Aug from the old NUC being used since 2016.  NUC system shows "End of day needed!" and this system has not had the end of day process followed for years.  When viewing from "Today's Revenue & Productivity" on the Nuc all the transactions and totals show on the correct day.  Their last day of sales was on 1 Aug (Sunday) and viewing after that all the way to today shows there were no transactions.  

I restore the /dat folder on a fresh image on a Raspberry Pi 4.   After copied I reboot, and launch Viewtouch from the desktop.  Everything seems okay except when viewing "Today's Revenue & Productivity".  All the transactions from 1 Aug 2021 now show up on 6 Aug 2021 and all past transactions are shifted relatively.  I should mention I did manually set the system clock before copying and launching Viewtouch since the PI has no RTC and it is not online.  

I wonder if this has anything to do with the time/date setting on the Raspberry Pi?  Or because on the Nuc they didn't do End of Day which has resulted in 18,769 check_xxxx files in the dat/current/ folder?

**Comment by jcrafty** [comment]
I took another backup today.  This time I didn't use a USB Fat32 drive but formatted it EXT4 in case files details were note being persevered and this mattered.

Last sales were done on Sunday 8 Aug.  When I restore the /dat folder to the Raspberry Pi (from the Nuc) all transactions are shifted 5 days into the future.  Sunday's totals show on Friday 13 Aug.  This is consistent with all other observations.  I confirmed both the Nuc and the Pi have the correct system date/time.   Any ideas how to get the dates to show on the correct date on the Pi?

**Comment by NeroBurner** [comment]
Do you find any dates, that aren't shifted outside of the revenue/archive? Asking to check if we have a general "date is parsed different on arm64 and amd64" or if it is something else

**Comment by GeneMosher** [comment]
At 'End of Day', all of the day's transactions are saved in a file named with a six digit serial number.  The number is incremented from the file name for the previous day and is written to the /usr/viewtouch/dat/archive directory.  If no 'End of Day' is performed then the transactions to be saved span the entire period of days since the last 'End of Day' was performed.  In this case the number of days is some number greater than several hundred.  When designing the building of the sales history we considered making 'End of Day' automatic but decided against making 'End of Day' automatic.  I have since given a lot of thought about the performance of the End of Day code and the writing of the file to be made without the explicit assent of the user.  The code performed at end of day is automatic but End of Day requires +that there are no 'Open Checks' (i.e., incomplete transactions).  If End of Day is to made automatic then the issue of how 'Open Checks' is to be handled.  Currently, End of Day can be performed OPTIONALLY by allowing Open Checks to remain open !  This provision was written into the code so that restaurant which are open 24 hours each day can have End of Day without finalizing Guest Checks.

It must be noted that in the past year the code ViewTouch uses for time and date has been entirely refactored.  ViewTouch currently uses Howard Hinnant's date and time library.  It is entirely possible that this problem is the result of ViewTouch code which is no longer in use and that the new date and time library prevents this problem from happening in the current code base.

It may not be practical or even be possible either to figure out what causes this 'offset' problem or how to correct it. If there's any good news regarding this problem it is that no one else has reported it.  I am inclined to suggest that a print or screenshot(s) of the significant facts from the historical data can be made, then delete the contents of /usr/viewtouch/dat/archive and begin anew to build the history of transactions in the archive directory.  It is not unusual to simply settle for a solution to a problem which allows for a way forward but which doesn't involve understanding why the problem exists.

We really have no choice going forward other than to spend the resources we have on any of the other many things we can do to improve ViewTouch, especially for issues which affect all ViewTouch customers and users.
