### ISSUE TITLE
conf_file setValue does not what comment says

### ISSUE THREAD

**Issue by NeroBurner** [ViewTouch/viewtouch#28]
https://github.com/ViewTouch/viewtouch/blob/18a4d9644f69d04dc99ef015429996a4a0d06798/conf_file.cc#L170-L180

The comment says, that the entry is created if the value is not "", but there is no check for empty string (neither key nor value). Should I add the check or just remove the comment?

**Comment by GeneMosher** [comment]
I'm fine with whatever you feel is best but it seems to me that if the condition of the test can possibly be met then a check for empty string should be in there and handled if it is found.
I suspect there are lines of code that are never actually executed, and of course, a profile would tell us which lines of code are more often executed than any others are.  Most people building the code over the years (and fortunately not all) were not capable of applying an analysis of the code execution profile or even of using the GNU debugger.  Some, like Jack Morrison were capable of this and Jack was able to find and fix some bugs that others were unable to find.
I have always wished that when ViewTouch crashed (which is not often) there would automatically be a dump of information which would at least tell us which function was being performed when the crash occurred.  We have some pretty good code here but there is always room for improvement, and it takes the best of the best developers to find what the weak points in the code are.  You have given me hope again for the application of such development techniques and I am quite grateful for that, I trust that you know.  In putting ViewTouch under GPL3 I had hoped that we could see ViewTouch taken to a new level and the contributions offered since the license change in late 2014 have made me very appreciative of the work that several developers have made in the past 3 1/2 years.

**Comment by NeroBurner** [comment]
I've now checked keyName and value for empty strings not allowing entries like `=value` and `key=`. It now has to be `key=value`

I don't yet know hot to generate coverage reports, but I know that unittests have always eased my mind when refactoring code. I'll see if I can add some tests to this project

as to the automatic dump: I have no Idea how to do it, but if I've got an idea I will let you know :)

you put a smile on my face. I'm happy to contribute to a project with such a great persion behind it :+1:
