### ISSUE TITLE
Remove Update functionality

### ISSUE THREAD

**Issue by NeroBurner** [ViewTouch/viewtouch#42]
Can we remove the automatic remote update functionality from Viewtouch? For example in `manager.cc`. I don't think this functionality is used anymore

**Comment by GeneMosher** [comment]
What that function is supposed to do is to ensure that everyone has the latest version of the vt_data graphics file.  It would be better if it worked the way it's supposed to.  Actually, Jack Morrison, a very capable developer, had written it so that it worked nicely but there was some complexity about it which I didn't understand well enough, so I didn't do what I was supposed to be doing to make it work the way Jack had coded it.  It would be great if everyone would automatically have the latest version of vt_data, actually, but it would also be great if I could just upload the latest vt_data file to the ViewTouch web site and the ViewTouch app would simply look there to get it and pull it down if it was a more recent version of that file than the one that they might already have.

**Comment by GeneMosher** [comment]
I have also made an effort to write a script which would check to see if the latest GitHub source has been compiled and installed on the Raspberry Pi.  If new source code is available then the RPi script would pull it down, compile and install it.  I'll send my script to you so you can evaluate it.  I have only ever written this one bash script and it does work, but as everyone knows, I am not a developer, or script writer.  My feeling with regard to everyone having the latest binary is the same as everyone having the latest vt_data file.  I would, consequently, also be fine with automatic updating of all packages from Raspbian which the production RPi image of ViewTouch uses.
