### ISSUE TITLE
Revenue & Productivity Report Bug

### ISSUE THREAD

**Issue by GeneMosher** [ViewTouch/viewtouch#60]
One of the few remaining bugs is in the "Reports" area when selecting "Accounting: Receipts Balance & Cash Deposit" report.  Selecting this causes the program to crash.

**Comment by NeroBurner** [comment]
I've narrowed the problem in 'Revenue & Productivity Report' down

When cycling through the report periods the `period_view` variable is incremented

https://github.com/ViewTouch/viewtouch/blob/f72b1137d61a1f624eb8c181ebbbf52da67de303/zone/report_zone.cc#L752-L756

`period_view` can take the following values:
```cpp
int ReportPeriodValue[] = {
    SP_NONE, SP_DAY, SP_WEEK, SP_2WEEKS, SP_MONTH, SP_QUARTER, SP_YTD, -1 };
```

When `period_view` is of value `SP_YTD` the next value is `SP_NONE`. This is when things turn bad
```
1  raise                                           0x7fb39a126d7f 
2  abort                                           0x7fb39a111672 
3  __assert_fail_base.cold.0                       0x7fb39a111548 
4  __assert_fail                                   0x7fb39a11f396 
5  TimeInfo::operator>       time_info.cc     426  0x5623c0a853f6 
6  WorkEntry::Overlap        labor.cc         370  0x5623c09cc645 
7  LaborDB::FigureLabor      labor.cc         1313 0x5623c09d0bc2 
8  BalanceReportWorkFn       system_report.cc 1557 0x5623c09e5271 
9  ??                                              0x7fb39b189c2e 
10 XtAppNextEvent                                  0x7fb39b18b493 
11 StartSystem               manager.cc       944  0x5623c092c999 
12 main                      manager.cc       454  0x5623c092a4cf 
```

The overlap between start and end should be calculated. But the member variable `start` is compared to the function variable `st` with the `>` operator. The variable `st` is not valid (`st.IsSet()` is false) and then the assert in TimeInfo hits

https://github.com/ViewTouch/viewtouch/blob/f72b1137d61a1f624eb8c181ebbbf52da67de303/main/labor.cc#L366-L372

FigureLabor checks the end time for validity, but not the start time
https://github.com/ViewTouch/viewtouch/blob/f72b1137d61a1f624eb8c181ebbbf52da67de303/main/labor.cc#L1290-L1313

The issue was silent before my changes, but is now hitting the new asserts. I don't know where `start` and `end` are set (or should be set) or how to resolve this issue.

**Comment by GeneMosher** [comment]
If I were a programmer I would be on this but I'm not, so I can't.  I'll write some emails to others to see if you and I can get some help on this.

**Comment by NeroBurner** [comment]
report bug probably fixed, but new image still available -> reopen

**Comment by NeroBurner** [comment]
title changed, therefore closing this bugreport as fixed
