### ISSUE TITLE
Segfault at button press

### ISSUE THREAD

**Issue by NeroBurner** [ViewTouch/viewtouch#61]
Sometimes when pressing a button rapidly a segmentation fault occurs a segmentation fault

```
1  XtRemoveTimeOut                              0x7fc227f40bc7 
2  RemoveTimeOutFn             manager.cc  2929 0x557c6d42b7c1 
3  Terminal::ClearSelectedZone terminal.cc 3153 0x557c6d444485 
4  Terminal::Mouse             terminal.cc 1536 0x557c6d43e13e 
5  Terminal::MouseInput        terminal.cc 4175 0x557c6d4488f7 
6  TermCB                      terminal.cc 267  0x557c6d4398b5 
7  ??                                           0x7fc227f4082d 
8  XtAppNextEvent                               0x7fc227f41570 
9  StartSystem                 manager.cc  944  0x557c6d423979 
10 main                        manager.cc  454  0x557c6d4214af 
```

Direct link to RemoveTimeOutFn https://github.com/ViewTouch/viewtouch/blob/f72b1137d61a1f624eb8c181ebbbf52da67de303/main/manager.cc#L2925-L2931

**Comment by GeneMosher** [comment]
Yes, I have noticed this, but I had not mentioned it to anyone.  Perhaps I should have ?!?!  It certainly is a bad enough bug, but it is a recent one, too.  It is the kind of bug that happens when the underlying X.org code changes.  ViewTouch code which handles the touchscreen input was written over 20 years ago at a time when there was little or no touchscreen support in the X.org code which deals with input devices.  That support does exist today but I don't believe ViewTouch code acknowledges this 'recent' support for touchscreens.

Long ago, before Linux, in 1986, the ViewTouch code base had been written to acknowledge the difference between a mouse click and a touch.  Each was handled differently and this was a very useful, superior way of handling input.  When the current version of ViewTouch was begun in 1995 the ViewTouch code base did not differentiate between a mouse click and a touch.  This was a step backward, admittedly.  I look forward to the day that touch input and a mouse click once again are differentiated - handled as separate events.  I have been told that this should not be difficult to achieve but no one except myself has regarded this as important enough to implement.  I would ask anyone to trust me that when a user is in 'Edit Mode' there is a BIG difference to users when a mouse click is differentiated from a touch.

For now, fixing this segfault is a very nice step forward.  Thanks for taking a look at it, NeroBurner.  See you in Vienna soon!  I'll be bringing some gear with me.

There is also a segfault if the screen is touched immediately after the program starts and reaches 'Page One'.  Likely the same code, I'm thinking.

**Comment by NeroBurner** [comment]
Hope this is fixed now

I'm also looking forward to see you
