### ISSUE TITLE
Graphics files

### ISSUE THREAD

**Issue by partoneoftwo** [ViewTouch/viewtouch#8]
The graphics files - These should be comitted to this repository as well.
How can they be added by a user, can they be designed by a user? If so, which resolutions?

**Comment by GeneMosher** [comment]
There are two 'sides' when it comes to looking at ViewTouch Graphics files.  On one side there are 'System Pages' which are common to all ViewTouch users and there are several kinds of other pages which are specific to individual ViewTouch users.  There is a particular issue with the graphics files which contain the System Pages because in the same way that changes to the source code can break the software, so too can changes to the System Pages break the software's user interface.  The reason System Pages exist is to provide a GUI foundation which is universally useful and which requires no changes by most users.  The portions of the GUI which users need to 'Edit' and customize is easily accessed and offers quite an extensive selection of 'Drag & Drop' tools.  There is a manual at the ViewTouch Download web page which explains how these tools work.  There is also a help page within ViewTouch which further explains this.  As I learn how to make the Graphics Starter Fileset available at GitHub then I'll do this.

**Comment by Steve132** [comment]
Want me to commit the graphics files to the repo in the right place?  Shouldn't be too hard I don't think

**Comment by GeneMosher** [comment]
On 05/13/2015 12:08 PM, Steven Braeger wrote:
>
> Want me to commit the graphics files to the repo in the right place?
> Shouldn't be too hard I don't think
>

I think so, yes, but if possible I want to be the only person who can
update them for now.  When people start screwing with the System Pages
the results are as bad as somebody screwing with the source code for the
hell of it who has no idea what they're doing.

**Comment by st1nga** [comment]
Any news on the graphic files?

**Comment by GeneMosher** [comment]
ViewTouch will now automatically download the graphics files which represent the 'System Pages" from the ViewTouch web site.  The next step will be for ViewTouch to automatically download a minimal or starting set of pages for table management and menus.  This should be complete by December 1st.
